import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import { AuthGuard } from '@/app/_components/Auth/AuthGuard'
import { MainLayout } from '@/app/_components/Layout/main'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthGuard>
          <MainLayout>
            <div id='main-content' className="text-slate-900 sm:p-4 w-full h-full overflow-y-scroll bg-slate-100 rounded-xl">
              {children}
              </div>
          </MainLayout>
        </AuthGuard>
      </body>
    </html>
  )
}

